Doggo/urls.py
from django.conf.urls import url

from . import views

app_name = 'Doggo'
urlpatterns = [
    # ex: /Doggo/details
    url(r'^$', views.introView, name='intro'),
    url(r'^wybory/(?P<wybory_id>[0-9]+)/$', views.detail_wybory, name='detail_wybory'),
    url(r'^kandydat/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<wybory_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^wybory/(?P<wybory_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^tworcy$', views.creatorsview, name='creators'),
    url(r'^upcoming$', views.UpcomingView.as_view(), name='upcoming'),
    url(r'^previous$', views.PreviousView.as_view(), name='previous'),
    url(r'^home', views.HomeView.as_view(), name='home')
]

eWybory/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from Doggo import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^Doggo/', include('Doggo.urls')),
    url(r'^admin/', admin.site.urls),
]

Doggo/models.py
from django.db import models

# Create your models here.
class Partia(models.Model):
    nazwa = models.CharField(max_length=40)

    __tablename__ = 'Partia'

    def __str__(self):
        return self.nazwa


class Wybory(models.Model):
    id = models.AutoField(primary_key=True)
    typ = models.CharField(max_length=30)
    start_time = models.DateField()
    end_time = models.DateField()
    maxKandydatow = models.IntegerField(default=0)
    # czasWyboru = models.IntegerField(default=0)

    __tablename__ = 'Wybory'

    def __str__(self):
        return "%s" % (self.typ)


class Kandydat(models.Model):
    id = models.AutoField(primary_key=True)
    imie = models.CharField(max_length=15)
    nazwisko = models.CharField(max_length=20)
    licznik = models.IntegerField(default=0)
    partia = models.ForeignKey(Partia, on_delete=models.CASCADE)
    wybory = models.ForeignKey(Wybory, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s - %s" % (self.imie, self.nazwisko, self.partia)


class Glosujacy(models.Model):
    id = models.AutoField(primary_key=True)
    pesel = models.BigIntegerField(unique=True)

    def __str__(self):
        return "%d" %self.pesel


class Glos(models.Model):
    id = models.AutoField(primary_key=True)
    glosujacy = models.ForeignKey(Glosujacy, on_delete=models.CASCADE)
    wybory = models.ForeignKey(Wybory, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.wybory, self.glosujacy)


class Kandydowanie(models.Model):
    kandydat = models.ForeignKey(Kandydat, on_delete=models.CASCADE)
    wybory = models.ForeignKey(Wybory, on_delete=models.CASCADE)
    __tablename__ = 'Kandydowanie'

    def __str__(self):
        return "%s %s w wyborach %s" % (self.kandydat.imie, self.kandydat.nazwisko, self.wybory.typ)

Doggo/views.py
import datetime
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Kandydat, Wybory, Glos, Glosujacy

# Create your views here


class ResultsView(generic.DetailView):
    model = Wybory
    template_name = ''


def vote(request, wybory_id):
    wybory = get_object_or_404(Wybory, pk=wybory_id)
    kandydat_list = Kandydat.objects.filter(wybory_id=wybory_id).order_by('nazwisko')
    try:
        selected_choice = get_object_or_404(Kandydat, pk=request.POST['choice'])
        user = Glosujacy.objects.get(pesel=request.POST['pesel'])
        glos = Glos.objects.filter(
            wybory__exact=wybory
        ).filter(
            glosujacy__exact=user
        )

        if glos.count() == 0:
            glos = Glos(wybory=wybory, glosujacy=user)
            glos.save()
            selected_choice.licznik += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('Doggo:home'))
        else:
            return render(request, 'detail_wybory.html', {
                'wybory': wybory,
                'kandydat_list': kandydat_list,
                'error_message': "Ta osoba juz glosowala w tych wyborach",
            })
    except (KeyError, Glosujacy.DoesNotExist, Kandydat.DoesNotExist):
        return render(request, 'detail_wybory.html', {
            'wybory': wybory,
            'kandydat_list': kandydat_list,
            'error_message': "Pesel nie znajduje sie w bazie glosujacych",
        })


class HomeView(generic.ListView):
    template_name = 'home.html'
    context_object_name = 'home_list'

    def get_queryset(self):
        return Wybory.objects.exclude(
            start_time__gte=datetime.date.today()
        ).filter(
            end_time__gte=datetime.date.today()
        ).order_by('end_time')


class UpcomingView(generic.ListView):
    template_name = 'upcoming.html'
    context_object_name = 'upcoming_list'

    def get_queryset(self):
        return Wybory.objects.filter(
            start_time__gte=datetime.date.today()
        ).order_by('start_time')


class PreviousView(generic.ListView):
    template_name = 'previous.html'
    context_object_name = 'previous_list'

    def get_queryset(self):
        return Wybory.objects.filter(
            end_time__lt=datetime.date.today()
        ).order_by('end_time')


class DetailView(generic.DetailView):
    model = Kandydat
    template_name = 'detail.html'


def detail_wybory(request, wybory_id):
    wybory = get_object_or_404(Wybory, pk=wybory_id)
    kandydat_list = Kandydat.objects.filter(wybory_id=wybory_id).order_by('nazwisko')
    context = {
        'wybory': wybory,
        'kandydat_list': kandydat_list,
    }
    return render_to_response('detail_wybory.html', context)


def introView(request):
    return render_to_response('intro.html')

def results(request, wybory_id):
    wybory = get_object_or_404(Wybory, pk=wybory_id)
    kandydat_list = Kandydat.objects.filter(wybory_id=wybory_id).order_by('nazwisko')
    liczba_dopuszczonych = Glosujacy.objects.all().count()
    liczba_glosujacych = Glos.objects.filter(wybory_id=wybory_id).count()
    frekwencja = liczba_glosujacych / liczba_dopuszczonych * 100
    context = {
        'wybory': wybory,
        'kandydat_list': kandydat_list,
        'frekwencja': frekwencja,
    }
    return render_to_response('results.html', context)


def creatorsview(request):
    creators = {"Marek Jakubowski", "Piotr Otapowicz", "Karol Wojciula"}
    context = {'creators': creators}
    return render_to_response("creators.html", context)

Doggo/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>eWybory</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'bootstrap/css/simple-sidebar.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="{% url 'Doggo:intro' %}">
                    eWybory
                </a>
            </li>
            <li>
                <a href="{% url 'Doggo:home' %}">Aktualne wybory</a>
            </li>
            <li>
                <a href="{% url 'Doggo:upcoming' %}">Nadchodzace wybory</a>
            </li>
            <li>
                <a href="{% url 'Doggo:previous' %}">Wyniki zakonczonych wyborow</a>
            </li>
            <li>
                <a href="{% url 'Doggo:creators' %}">Tworcy</a>
            </li>
            <img src="{% static 'images/addonimage.jpg' %}" class="stretch" align="center">

    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <a href="#menu-toggle" class="btn btn-info btn-block" id="menu-toggle">Menu</a>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12" style="text-align: center">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static 'bootstrap/js/jquery.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


<!-- Menu Toggle Script -->
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

</body>

</html>

Doggo/templates/creators.html
{% extends "base.html" %}

{% block content %}
<ul>
 {% for mozejamozety in creators %}
        <h1>{{ mozejamozety }}</h1><br>
    {% endfor %}
</ul>
{% endblock %}

Doggo/templates/detail_wybory.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ wybory.typ }}</h2>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in kandydat_list %}

        <form action="{% url 'Doggo:vote' wybory.id %}" method="post">
        <label class="btn btn-outline-primary">
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice }}</label>
        </label>
        <br/>
    {% endfor %}
    <br>
<label>Pesel*: </label>
<input type="number" name="pesel" required="true"><br/>
<input type="submit" value="Vote"/>
</form>
{% endblock %}










{#<ul>#}
{#    {% for Kandydat in kandydat_list %}#}
{#        <li><a href="/Doggo/kandydat/{{ Kandydat.id }}/">{{ Kandydat.imie }} {{ Kandydat.nazwisko }}</a></li>#}
{#        <li><a href="{% url 'Doggo:vote' Kandydat.id %}">{{ Kandydat.imie }} {{ Kandydat.nazwisko}}</a></li>#}
{#    {% endfor %}#}
{#</ul>#}

Doggo/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if home_list %}
<ul>
    {% for Wybory in home_list %}
       <a href="/Doggo/wybory/{{ Wybory.id }}/"><font size="5"> {{ Wybory.typ }} - otwarte do {{ Wybory.end_time }}</font></a><br>
{#        <li><a href="{% url 'Doggo:wybory' wyboryy.id %}">{{ Wybory.typ }}</a></li>#}
    {% endfor %}
</ul>
{% else %}
<p>Brak otwartych wyborów.</p>
{% endif %}
{% endblock %}

Doggo/templates/intro.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <h1>eWybory</h1>
    <p>Projekt zrealizowany na zajeciach z Rozwiazan szkieletowych w tworzeniu aplikacji</p>
    <p>Jezyk programowania: Python</p>
    <p>Framework: Django</p>
    <div id="github" style="text-align: center">
    <a href="https://github.com/dotrek/eWybory"> <img src="{% static 'images/GitHub-Mark-64px.png' %}"/></a>
    </div>
{% endblock %}

Doggo/templates/previous.html
{% extends "base.html" %}

{% block content %}
{% if previous_list %}
<ul>
    {% for Wybory in previous_list %}
        <font size="5"><a href="/Doggo/{{ Wybory.id }}/results/">{{ Wybory.typ }} - otwarte do {{ Wybory.end_time }}</a></br></font>
{#        <a href="{% url 'Doggo:results' wybory.id %}">{{ Wybory.typ }} ({{ Wybory.start_time }}-{{ Wybory.end_time }}</a></br></font>#}
    {% endfor %}
</ul>
{% else %}
<p>Brak historii wyborów.</p>
{% endif %}
{% endblock %}

Doggo/templates/results.html
{% extends "base.html" %}
{% block content %}
<h1>{{ wybory.typ }}</h1>

<ul>
    {% for Kandydat in kandydat_list %}
    <li>{{ Kandydat.nazwisko }} -- {{ Kandydat.licznik }} vote{{ Kandydat.licznik|pluralize }} </li>
    {% endfor %}
</ul>
<p>Frekwencja wyniosla: <strong>{{ frekwencja }}%</strong></p>
{% endblock %}

Doggo/templates/upcoming.html
{% extends "base.html" %}

{% block content %}
{% if upcoming_list %}
<ul>
    {% for Wybory in upcoming_list %}
         <font size="5" color="#428bca">{{ Wybory.typ }} -  w dniach: {{ Wybory.start_time }} - {{ Wybory.end_time }}</br></font>
    {% endfor %}
</ul>
{% else %}
<p>Brak nadchodzących wyborów.</p>
{% endif %}
{% endblock %}